### PR TITLE
Remove boost requirement

### LINKED ISSUE #115: 🐛  Doesn't respect channel's default archive duration
### Describe the bug

Hi!
Thanks for creating and hosting the bot, I really appreciate it!

I'm currently using the hosted version and the server I've added it to has the maximum boost level, so one can set the archive duration to 1 week.

In https://github.com/MarcusOtter/discord-needle/pull/34 I saw:

> to clamp the auto-archive duration to the maximum ACTUAL allowed value

I understand the reasoning for this at that time but I think it's a bug that the default duration that is selected for the channel is not evaluated first before falling back to the actual allowed value.

So I'm talking about this channel setting at the bottom:

Bildschirmfoto 2022-03-21 um 10 11 25

Right now Needle sets every thread to 1 week which is too long, I want to have it at 24 hours.

### Steps to reproduce the bug

1. Server with boosted levels to have more duration than 1 week
2. Set default duration to 24 hours in channel
3. Needle uses boosted options, not 24 hours

### Expected behavior

I expect the following:

- Use channel setting
- If channel setting is set to something that doesn't exist anymore (as server is not boosted anymore) fallback to current max value behavior

### LINKED ISSUE #156: 💡 Remove boost requirement for auto-archive duration
### Describe the improvement

Discord updated their API recently and removed the server boost requirement for thread auto-archive durations. The workarounds that Needle does because of the previously glitchy API should now be removed.

Removal of boost requirement: https://github.com/discord/discord-api-docs/pull/4825

### Problems this improvement solves

Removes dead code, and solves #115

### Alternative solutions

N/A

### LINKED ISSUE #157: 🐛 Needle sometimes deletes the button message
### Describe the bug

If Needle is given the "Manage messages" permission it will automatically pin the button message and remove the "Needle pinner a message to this channel" system message. However, sometimes it will accidentally remove the button message instead:

image

### Steps to reproduce the bug

1. Enable auto-threading
2. Give Needle the "Manage messages" permission
3. Spam message in the auto-thread channel
4. See some of the threads get this bug (race condition)

### Expected behavior

Only the system message is removed.

### PR DESCRIPTION
**Pull request by MarcusOtter**
Removes the boost requirement for auto-archive duration and fixes a bug with the pin message features that I found during testing

Closes #115
Closes #156
Closes #157

### CODE REVIEW

**Review by c43721 — APPROVED** [review]

File: src/helpers/promiseHelpers.ts [hunk 1]
```diff
@@ -0,0 +1,3 @@
+export function wait(milliseconds: number): Promise<void> {
```
Comment (nchristopher) [inline src/helpers/promiseHelpers.ts:1]: Is `promiseHelpers.ts` an appropriate name for this file? I think just `wait.ts` would be better.

Comment (MarcusOtter) [reply src/helpers/promiseHelpers.ts:1]: I'm thinking it's a good file to put helper functions for various promises, if any in the future. We don't really do one file per function anywhere else in Needle so I don't think naming the file after the function follows what we do right now
